### ISSUE TITLE
Error While Processing Data From ServerList!

### ISSUE THREAD

**Issue by FienixEC** [SalmonDE/FishyUpdater#1]
Getting this error below on console after every update event, and in game floating votes text wont display, any help on this?

2017-05-01 [Tesseract] [17:20:49] WARNING> [TopVoter] Error while processing data from the serverlist!
2017-05-01 [Tesseract] [17:20:49] ERROR> [TopVoter] 
2017-05-01 [Tesseract] [17:20:49] ERROR> [TopVoter] Raw: {
"name":"MineZoneRP",
"address":"minezonerp.com",
"port":"19132",
"month":"201705",
"voters": [
{
"nickname":"RiversSon_Zero",
"votes":"1"	},	{
"nickname":"LeMatrix",
"votes":"1"	},	{
"nickname":"Bruh_itz_Alen",
"votes":"1"	},	{
"nickname":"xXchloroboneXx",
"votes":"1"	},	{
"nickname":"lklahm",
"votes":"1"	}	]
}

**Comment by FienixEC** [comment]
oops

**Comment by SalmonDE** [comment]
Not related to this repository
